name: build
on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  sonar-analysis:
    uses: ArquisoftV-Microservice-Project/devops-workflows/.github/workflows/build.yml@main
    with:
      namespace: backend
    secrets: inherit
