name: SonarQube Analysis
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

    
jobs:
  sonar-analysis:
    uses: ArquisoftV-Microservice-Project/devops-workflows/.github/workflows/sonar.yml@main
    secrets: inherit